"""Centralized feasibility reason-code enum (Phase 6).

A single source of truth for every code FeasibilityService can emit —
routes, the Gemini tool, and the frontend all import from here rather
than re-declaring string literals. Only codes actually implemented by
FeasibilityService appear (docs/DECISIONS.md ADR-040 family).
"""

from __future__ import annotations

from enum import StrEnum


class FeasibilityReasonCode(StrEnum):
    EXPERIENCE_INACTIVE = "EXPERIENCE_INACTIVE"
    MISSING_LOCATION = "MISSING_LOCATION"

    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE"
    UNSUPPORTED_CURRENCY = "UNSUPPORTED_CURRENCY"

    DURATION_EXCEEDED = "DURATION_EXCEEDED"
    DURATION_UNAVAILABLE = "DURATION_UNAVAILABLE"

    OUTSIDE_AVAILABLE_TIME = "OUTSIDE_AVAILABLE_TIME"

    OPENING_HOURS_CONFLICT = "OPENING_HOURS_CONFLICT"
    OPENING_HOURS_UNAVAILABLE = "OPENING_HOURS_UNAVAILABLE"

    TRAVEL_TIME_EXCEEDED = "TRAVEL_TIME_EXCEEDED"
    TRAVEL_TIME_UNAVAILABLE = "TRAVEL_TIME_UNAVAILABLE"
    MAX_DISTANCE_EXCEEDED = "MAX_DISTANCE_EXCEEDED"

    GROUP_SIZE_EXCEEDS_CAPACITY = "GROUP_SIZE_EXCEEDS_CAPACITY"
    CAPACITY_UNAVAILABLE = "CAPACITY_UNAVAILABLE"

    ACCESSIBILITY_NOT_SUPPORTED = "ACCESSIBILITY_NOT_SUPPORTED"
    ACCESSIBILITY_DATA_UNAVAILABLE = "ACCESSIBILITY_DATA_UNAVAILABLE"

    AVAILABILITY_CONFLICT = "AVAILABILITY_CONFLICT"
    AVAILABILITY_UNAVAILABLE = "AVAILABILITY_UNAVAILABLE"

    ITINERARY_CONFLICT = "ITINERARY_CONFLICT"

    MISSING_TIME_CONTEXT = "MISSING_TIME_CONTEXT"
    MISSING_ORIGIN = "MISSING_ORIGIN"
    ROUTE_UNAVAILABLE = "ROUTE_UNAVAILABLE"

    # ─── Phase 8: itinerary composition / post-composition validation ──────
    # Reuse this same enum (never a parallel free-form string set) for
    # schedule-level and itinerary-level checks in itinerary_validator.py.
    EXPERIENCE_NOT_FEASIBLE = "EXPERIENCE_NOT_FEASIBLE"
    SCHEDULE_OVERLAP = "SCHEDULE_OVERLAP"
    SCHEDULE_NOT_CHRONOLOGICAL = "SCHEDULE_NOT_CHRONOLOGICAL"
    TRAVEL_TRANSITION_IMPOSSIBLE = "TRAVEL_TRANSITION_IMPOSSIBLE"
    DUPLICATE_EXPERIENCE = "DUPLICATE_EXPERIENCE"
    OUTSIDE_REQUESTED_WINDOW = "OUTSIDE_REQUESTED_WINDOW"
    ITINERARY_BUDGET_EXCEEDED = "ITINERARY_BUDGET_EXCEEDED"
    ITINERARY_COUNT_LIMIT_EXCEEDED = "ITINERARY_COUNT_LIMIT_EXCEEDED"
    ITINERARY_EMPTY = "ITINERARY_EMPTY"
    INVALID_BUFFER = "INVALID_BUFFER"
    CUSTOM_ACTIVITY_CONFLICT = "CUSTOM_ACTIVITY_CONFLICT"
    CUSTOM_TRAVEL_UNVERIFIED = "CUSTOM_TRAVEL_UNVERIFIED"


__all__ = ["FeasibilityReasonCode"]
