"""phase9_realtime_context_replanning

Revision ID: 04763f8eec67
Revises: 8a004268dcb0
Create Date: 2026-09-24 12:59:07.058197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04763f8eec67'
down_revision: Union[str, Sequence[str], None] = '8a004268dcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_snapshots',
    sa.Column('context_type', sa.Enum('WEATHER', 'EVENTS', name='context_snapshot_type', native_enum=False), nullable=False),
    sa.Column('scope_key', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_version', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_context_snapshots_type_scope', ['context_type', 'scope_key'], unique=False)

    op.create_table('itinerary_revisions',
    sa.Column('itinerary_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_revision_id', sa.String(length=36), nullable=True),
    sa.Column('trigger', sa.Enum('USER_REQUESTED', 'TIME_CHANGED', 'BUDGET_CHANGED', 'PARTY_SIZE_CHANGED', 'WEATHER_CHANGED', 'EVENT_CANCELLED', 'EVENT_RESCHEDULED', 'EVENT_VENUE_CHANGED', 'AVAILABILITY_CHANGED', name='replan_trigger', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('REPLANNED', 'NO_CHANGE', 'REPLAN_FAILED', 'REQUIRES_USER_ACTION', name='itinerary_revision_status', native_enum=False), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('context_snapshot_reference', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'idempotency_key', name='uq_itinerary_revision_idempotency')
    )
    with op.batch_alter_table('itinerary_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_revisions_itinerary_id'), ['itinerary_id'], unique=False)
        batch_op.create_index('ix_itinerary_revisions_itinerary_id_version', ['itinerary_id', 'version'], unique=False)

    # Every new NOT NULL column below carries an explicit server_default
    # so this migration is safe against a non-empty table (SQLite/Postgres
    # both require a default when adding a NOT NULL column to existing
    # rows) — matches the Enum/native_enum=False portability pattern
    # already established in Phase 6/8 migrations.
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environmental_type', sa.Enum('INDOOR', 'OUTDOOR', 'MIXED', 'UNKNOWN', name='experience_environmental_type', native_enum=False), nullable=False, server_default='UNKNOWN'))
        batch_op.add_column(sa.Column('weather_sensitivity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'UNKNOWN', name='experience_weather_sensitivity', native_enum=False), nullable=False, server_default='UNKNOWN'))
        batch_op.add_column(sa.Column('weather_policy', sa.Enum('NONE', 'LIGHT_RAIN_OK', 'WEATHER_SENSITIVE', 'SEVERE_WEATHER_EXCLUDE', name='experience_weather_policy', native_enum=False), nullable=False, server_default='NONE'))

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('current_revision_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('replanning_status', sa.String(length=30), nullable=False, server_default='STABLE'))
        batch_op.add_column(sa.Column('context_last_updated_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('itinerary_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('item_state', sa.String(length=20), nullable=False, server_default='ACTIVE'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_items', schema=None) as batch_op:
        batch_op.drop_column('item_state')
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_column('context_last_updated_at')
        batch_op.drop_column('replanning_status')
        batch_op.drop_column('current_revision_id')
        batch_op.drop_column('version')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('weather_policy')
        batch_op.drop_column('weather_sensitivity')
        batch_op.drop_column('environmental_type')

    with op.batch_alter_table('itinerary_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_itinerary_revisions_itinerary_id_version')
        batch_op.drop_index(batch_op.f('ix_itinerary_revisions_itinerary_id'))

    op.drop_table('itinerary_revisions')
    with op.batch_alter_table('context_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_context_snapshots_type_scope')

    op.drop_table('context_snapshots')
    # ### end Alembic commands ###
