"""phase12_experience_images

Revision ID: 0572944927a4
Revises: cd1a9dcd5325
Create Date: 2026-09-25 22:51:49.000392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0572944927a4'
down_revision: Union[str, Sequence[str], None] = 'cd1a9dcd5325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('image_thumbnail_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('image_source', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('image_source_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('image_source_id', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image_license', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('image_license_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_author', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image_attribution_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_is_place_specific', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_is_synthetic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_match_method', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('image_match_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image_retrieved_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('image_retrieved_at')
        batch_op.drop_column('image_match_score')
        batch_op.drop_column('image_match_method')
        batch_op.drop_column('image_is_synthetic')
        batch_op.drop_column('image_is_place_specific')
        batch_op.drop_column('image_attribution_text')
        batch_op.drop_column('image_author')
        batch_op.drop_column('image_license_url')
        batch_op.drop_column('image_license')
        batch_op.drop_column('image_source_id')
        batch_op.drop_column('image_source_url')
        batch_op.drop_column('image_source')
        batch_op.drop_column('image_thumbnail_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
