"""phase7_personalization

Revision ID: 514cfa85d6b6
Revises: 6762a731d1f1
Create Date: 2026-09-24 02:11:16.239522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514cfa85d6b6'
down_revision: Union[str, Sequence[str], None] = '6762a731d1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler_affinities',
    sa.Column('traveler_id', sa.String(length=36), nullable=False),
    sa.Column('dimension_type', sa.String(length=30), nullable=False),
    sa.Column('dimension_key', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traveler_id', 'dimension_type', 'dimension_key', name='uq_traveler_affinity_dim')
    )
    op.create_index(op.f('ix_traveler_affinities_traveler_id'), 'traveler_affinities', ['traveler_id'], unique=False)
    op.create_index('ix_traveler_affinities_traveler_id_dim_type', 'traveler_affinities', ['traveler_id', 'dimension_type'], unique=False)
    op.create_table('traveler_preferences',
    sa.Column('traveler_id', sa.String(length=36), nullable=False),
    sa.Column('preferred_category_slugs', sa.JSON(), nullable=True),
    sa.Column('budget_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('preferred_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('preferred_max_distance_km', sa.Float(), nullable=True),
    sa.Column('accessibility_requirements', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traveler_id')
    )
    op.create_table('traveler_interactions',
    sa.Column('traveler_id', sa.String(length=36), nullable=False),
    sa.Column('experience_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('client_event_id', sa.String(length=100), nullable=False),
    sa.Column('recommendation_session_id', sa.String(length=36), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traveler_id', 'client_event_id', name='uq_traveler_interaction_client_event')
    )
    op.create_index(op.f('ix_traveler_interactions_experience_id'), 'traveler_interactions', ['experience_id'], unique=False)
    op.create_index(op.f('ix_traveler_interactions_traveler_id'), 'traveler_interactions', ['traveler_id'], unique=False)
    op.create_index('ix_traveler_interactions_traveler_id_created_at', 'traveler_interactions', ['traveler_id', 'created_at'], unique=False)
    op.create_index('ix_traveler_interactions_traveler_id_event_type', 'traveler_interactions', ['traveler_id', 'event_type'], unique=False)
    # SQLite cannot ALTER/DROP a constraint in place — batch mode does a
    # copy-and-move under the hood. PostgreSQL supports this natively and
    # batch_alter_table degrades to a plain ALTER there, so this is
    # portable across both (docs/DECISIONS.md dual-storage contract).
    with op.batch_alter_table('experience_embeddings') as batch_op:
        batch_op.drop_constraint(op.f('uq_experience_embeddings_experience_id'), type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience_embeddings') as batch_op:
        batch_op.create_unique_constraint(op.f('uq_experience_embeddings_experience_id'), ['experience_id'])
    op.drop_index('ix_traveler_interactions_traveler_id_event_type', table_name='traveler_interactions')
    op.drop_index('ix_traveler_interactions_traveler_id_created_at', table_name='traveler_interactions')
    op.drop_index(op.f('ix_traveler_interactions_traveler_id'), table_name='traveler_interactions')
    op.drop_index(op.f('ix_traveler_interactions_experience_id'), table_name='traveler_interactions')
    op.drop_table('traveler_interactions')
    op.drop_table('traveler_preferences')
    op.drop_index('ix_traveler_affinities_traveler_id_dim_type', table_name='traveler_affinities')
    op.drop_index(op.f('ix_traveler_affinities_traveler_id'), table_name='traveler_affinities')
    op.drop_table('traveler_affinities')
    # ### end Alembic commands ###
