"""phase8_itinerary_composer

Revision ID: 8a004268dcb0
Revises: 514cfa85d6b6
Create Date: 2026-09-24 09:52:43.475792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a004268dcb0'
down_revision: Union[str, Sequence[str], None] = '514cfa85d6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('traveler_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('itinerary_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'BOOKING_REQUESTED', 'COMPLETED', 'CANCELLED', name='itinerary_status', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('COMPOSER', 'MANUAL', name='itinerary_source', native_enum=False), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_travel_minutes', sa.Float(), nullable=True),
    sa.Column('estimated_total_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('narrative_title', sa.String(length=200), nullable=True),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('narrative_closing_message', sa.Text(), nullable=True),
    sa.Column('ranking_model_version', sa.String(length=40), nullable=True),
    sa.Column('narrative_model_version', sa.String(length=40), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itineraries_traveler_id'), ['traveler_id'], unique=False)
        batch_op.create_index('ix_itineraries_traveler_id_date_status', ['traveler_id', 'itinerary_date', 'status'], unique=False)

    op.create_table('itinerary_items',
    sa.Column('itinerary_id', sa.String(length=36), nullable=False),
    sa.Column('experience_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('travel_from_previous_minutes', sa.Float(), nullable=True),
    sa.Column('travel_from_previous_distance_km', sa.Float(), nullable=True),
    sa.Column('travel_mode', sa.String(length=20), nullable=True),
    sa.Column('buffer_before_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_after_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('source_rank_position', sa.Integer(), nullable=True),
    sa.Column('source_ranking_score', sa.Float(), nullable=True),
    sa.Column('narrative_text', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'sequence_order', name='uq_itinerary_item_sequence')
    )
    with op.batch_alter_table('itinerary_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_items_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_items_itinerary_id'), ['itinerary_id'], unique=False)
        batch_op.create_index('ix_itinerary_items_itinerary_id_experience_id', ['itinerary_id', 'experience_id'], unique=False)

    op.create_table('booking_requests',
    sa.Column('traveler_id', sa.String(length=36), nullable=False),
    sa.Column('itinerary_id', sa.String(length=36), nullable=False),
    sa.Column('itinerary_item_id', sa.String(length=36), nullable=False),
    sa.Column('experience_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('requested_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('traveler_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'DECLINED', 'CANCELLED', 'EXPIRED', name='booking_request_status', native_enum=False), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itinerary_item_id'], ['itinerary_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_requests_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_itinerary_id'), ['itinerary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_traveler_id'), ['traveler_id'], unique=False)
        batch_op.create_index('ix_booking_requests_traveler_provider_experience_itinerary_status', ['traveler_id', 'provider_id', 'experience_id', 'itinerary_id', 'status'], unique=False)

    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_search_candidates', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_column('last_search_candidates')

    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_requests_traveler_provider_experience_itinerary_status')
        batch_op.drop_index(batch_op.f('ix_booking_requests_traveler_id'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_provider_id'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_itinerary_id'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_experience_id'))

    op.drop_table('booking_requests')
    with op.batch_alter_table('itinerary_items', schema=None) as batch_op:
        batch_op.drop_index('ix_itinerary_items_itinerary_id_experience_id')
        batch_op.drop_index(batch_op.f('ix_itinerary_items_itinerary_id'))
        batch_op.drop_index(batch_op.f('ix_itinerary_items_experience_id'))

    op.drop_table('itinerary_items')
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_index('ix_itineraries_traveler_id_date_status')
        batch_op.drop_index(batch_op.f('ix_itineraries_traveler_id'))

    op.drop_table('itineraries')
    # ### end Alembic commands ###
