"""phase10_provider_intelligence

Revision ID: b5a57a5d120f
Revises: 04763f8eec67
Create Date: 2026-09-25 14:16:34.940622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a57a5d120f'
down_revision: Union[str, Sequence[str], None] = '04763f8eec67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_synthetic_demand_snapshots',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('experience_id', sa.String(length=36), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('completions', sa.Integer(), nullable=False),
    sa.Column('booking_requests', sa.Integer(), nullable=False),
    sa.Column('accepted_bookings', sa.Integer(), nullable=False),
    sa.Column('ratings_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('segment_type', sa.String(length=40), nullable=True),
    sa.Column('segment_key', sa.String(length=80), nullable=True),
    sa.Column('segment_label', sa.String(length=200), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_synthetic_demand_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_prov_synth_demand_provider_experience', ['provider_id', 'experience_id'], unique=False)
        batch_op.create_index('ix_prov_synth_demand_provider_period', ['provider_id', 'period_start', 'period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_synthetic_demand_snapshots_provider_id'), ['provider_id'], unique=False)

    op.create_table('provider_notifications',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('BEHAVIORAL_MATCH', 'BOOKING_REQUEST', 'DEMAND_ALERT', name='provider_notification_type', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('experience_id', sa.String(length=36), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('segment_summary', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('source_booking_request_id', sa.String(length=36), nullable=True),
    sa.Column('traveler_id', sa.String(length=36), nullable=True),
    sa.Column('cooldown_key', sa.String(length=32), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_booking_request_id'], ['booking_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_notifications', schema=None) as batch_op:
        batch_op.create_index('ix_provider_notifications_provider_cooldown', ['provider_id', 'cooldown_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_notifications_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index('ix_provider_notifications_provider_read_created', ['provider_id', 'is_read', 'created_at'], unique=False)
        batch_op.create_index('ix_provider_notifications_source_booking', ['source_booking_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_provider_notifications_source_booking')
        batch_op.drop_index('ix_provider_notifications_provider_read_created')
        batch_op.drop_index(batch_op.f('ix_provider_notifications_provider_id'))
        batch_op.drop_index('ix_provider_notifications_provider_cooldown')

    op.drop_table('provider_notifications')
    with op.batch_alter_table('provider_synthetic_demand_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_synthetic_demand_snapshots_provider_id'))
        batch_op.drop_index('ix_prov_synth_demand_provider_period')
        batch_op.drop_index('ix_prov_synth_demand_provider_experience')

    op.drop_table('provider_synthetic_demand_snapshots')
    # ### end Alembic commands ###
