"""phase11_safety

Revision ID: cd1a9dcd5325
Revises: b5a57a5d120f
Create Date: 2026-09-25 15:16:17.153825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1a9dcd5325'
down_revision: Union[str, Sequence[str], None] = 'b5a57a5d120f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('traveler_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_source', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_shared', sa.Boolean(), nullable=False),
    sa.Column('delivery_status', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traveler_id', 'idempotency_key', name='uix_traveler_idempotency')
    )
    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_alerts_traveler_id'), ['traveler_id'], unique=False)

    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('traveler_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_contacts_traveler_id'), ['traveler_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_traveler_id'))

    op.drop_table('emergency_contacts')
    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_alerts_traveler_id'))

    op.drop_table('emergency_alerts')
    # ### end Alembic commands ###
